### ISSUE TITLE
 Recurrence event is created on non-working days

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-calendar#562]
# Precondition
Working days are set except for the weekend (Saturday and Sunday)
![image](https://user-images.githubusercontent.com/69950655/119124379-c9c6bd00-ba5a-11eb-9d77-33606b107681.png)

# Actual Result
When creating the recurrence event, it generates events for both Saturday and Sunday
![image](https://user-images.githubusercontent.com/69950655/119124798-43f74180-ba5b-11eb-8cf4-db632776cd40.png)

# Expected Result
The recurrence event shouldn't be generated for non-working days

# Environment
DEV enironment

**Comment by alagane** [comment]
Are you talking about this? 
![image](https://user-images.githubusercontent.com/550970/119451015-09c8c100-bd35-11eb-950e-0ce86aeed9db.png)
If yes, it totally makes sense to repeat it every day since you can do what you want in the "repeat weekly".
The case where it should work like you say is if there is a checkbox "only working days" when repeating daily.
That's my opinion.

**Comment by tlle14** [comment]
Thank @alagane 
So this is not an issue. 
![image](https://user-images.githubusercontent.com/69950655/119451606-ac963500-bd5f-11eb-93f7-f26e85aacbef.png)
